### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by chatterjeesudip** [HappyLittleDog/SketchConf#1]
I am trying to build the code and I am getting the following issue - 
`/usr/bin/ld: /SketchConf/build/configurer/parser.tab.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/util.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/ast.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/configurer/configurer.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/experiment.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/hash/hash.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/simulation/streamgen.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/simulation/sketches/countminsketch.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/simulation/sketches/nitrosketch.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/simulation/sketches/countsketch.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/simulation/sketches/towersketch.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
/usr/bin/ld: /SketchConf/build/main.cpp.o:(.data+0x0): multiple definition of `TINY_SIM_NUM'; /SketchConf/build/configurer/lex.lex.cpp.o:(.data+0x4): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:91: all] Error 1`

**Comment by SheriffOreo** [comment]
Sorry for the compiling issue. It should be fixed already. Thanks for letting me know!
